name: Test Examples
on:
  push:
    branches: [main]
  pull_request:

jobs:

  # Collect all the individual projects
  test-collector:
    name: Test Collector
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: echo "matrix=$(ls ./circuits/examples | jq -R -s -c 'split("\n")[:-1]')" >> "$GITHUB_OUTPUT"

  # Shard across them all individually
  examples:
    runs-on: ubuntu-latest
    needs: [test-collector]
    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJson(needs.test-collector.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v2

      - name: Install Nargo
        uses: noir-lang/noirup@v0.1.2
        with:
          toolchain: nightly

      - name: Run Nargo test
        run: |
          cd circuits/examples/${{ matrix.target }}
          nargo test
